import reflex as rx
from calculator.state import State
from calculator import style


def keypad()->rx.Component:
    return rx.grid(
        rx.grid_item(
            rx.button(
                    "AC",
                    style=style.AC_button_style,
                    on_click=State.AC
                ), 
                row_span=1,col_span=2
            ),
        rx.grid_item(
            rx.button(
                    "del",
                    style=style.button_style,
                    on_click=State.delete
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "/",
                    style=style.button_style,
                    on_click=State.concat("/")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "7",
                    style=style.button_style,
                    on_click=State.concat("7")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "8",
                    style=style.button_style,
                    on_click=State.concat("8")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "9",
                    style=style.button_style,
                    on_click=State.concat("9")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "*",
                    style=style.button_style,
                    on_click=State.concat("*")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "4",
                    style=style.button_style,
                    on_click=State.concat("4")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "5",
                    style=style.button_style,
                    on_click=State.concat("5")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "6",
                    style=style.button_style,
                    on_click=State.concat("6")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "-",
                    style=style.button_style,
                    on_click=State.concat("-")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "1",
                    style=style.button_style,
                    on_click=State.concat("1")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "2",
                    style=style.button_style,
                    on_click=State.concat("2")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "3",
                    style=style.button_style,
                    on_click=State.concat("3")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "+",
                    style=style.button_style,
                    on_click=State.concat("+")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "( )",
                    style=style.button_style,
                    on_click=State.bracket
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "0",
                    style=style.button_style,
                    on_click=State.concat("0")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    ".",
                    style=style.button_style,
                    on_click=State.concat(".")
                ), 
                row_span=1,col_span=1
            ),
        rx.grid_item(
            rx.button(
                    "=",
                    style=style.button_style,
                    on_click=State.solve
                ), 
                row_span=1,col_span=1
            ),
        template_columns="repeat(4,1fr)",
        template_rows="repeat(5,1fr)",
        style=style.keypad_style
    )